baseURL = 'https://01io.dev/'

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Chao's garden"

# default language
defaultContentLanguage = "en"

# Author config
[author]
  name = "Chao"
  email = "csun01io@outlook.coms"
  link = ""

# Multilingual config
[languages]
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""

  [languages.zh-CN]
    languageCode = "zh-CN"
    languageName = "简体中文"
    weight = 2
    [languages.zh-CN.menu]
      [[languages.zh-CN.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "文章"
        url = "/posts/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
